<?php

return [
    'per_page' => 4,
    'tabs' => [
        ['id' => 'all', 'label' => 'Все страны'],
        ['id' => 'kz', 'label' => 'Казахстан'],
        ['id' => 'ru', 'label' => 'Россия'],
        ['id' => 'by', 'label' => 'Беларусь'],
    ],
    'projects' => [
        [
            'slug' => 'dom-olimp',
            'country' => 'kz',
            'title' => 'Дом «Олимп»',
            'year' => 'Проект реализован в 2023 году',
            'card_specs' => [
                'Площадь: 230 м²',
                'Этажность: 1 этаж',
                'Коллекция: Egoze',
                'Размер: 530x100x40',
                'Цвет: RB коричневый',
            ],
            'hero_image' => 'storage/img/projects/olimp-main.png',
            'hero_alt' => 'Дом Олимп — фасад в вечернее время',
            'description' => [
                'Дом «Олимп» — это минималистичный дом с четкой геометрией и панорамным остеклением. В экстерьере использован кирпич ручной формовки коллекции «Стиль Лофт» с глубоким графитовым оттенком и мягким рельефом.',
                'Основной акцент сделан на баланс фактуры кирпича и стеклянных фасадов. В интерьере теплый свет подчеркивает текстуру материалов и создает уютную атмосферу.',
            ],
            'brick_caption' => 'Использованные материалы',
            'brick_text' => 'Для фасада выбран кирпич RB-FB-CC-01 Antikstyle. Его неоднородный цвет и выразительная текстура делают архитектуру проекта визуально глубокой и современной.',
            'characteristics' => [
                ['label' => 'Площадь', 'value' => '230 м²'],
                ['label' => 'Этажность', 'value' => '1 этаж'],
                ['label' => 'Коллекция', 'value' => 'Egoze'],
                ['label' => 'Размер', 'value' => '530x100x40'],
                ['label' => 'Цвет', 'value' => 'RB коричневый'],
                ['label' => 'Локация', 'value' => 'г. Морозки'],
            ],
            'gallery' => [
                ['src' => 'storage/img/projects/olimp-gallery-1.png', 'alt' => 'Дом Олимп — ракурс 1'],
                ['src' => 'storage/img/projects/olimp-gallery-2.png', 'alt' => 'Дом Олимп — ракурс 2'],
                ['src' => 'storage/img/projects/olimp-gallery-3.png', 'alt' => 'Дом Олимп — панорамное остекление'],
                ['src' => 'storage/img/projects/olimp-gallery-4.png', 'alt' => 'Кладка кирпича крупным планом'],
            ],
        ],
        [
            'slug' => 'dom-sfera',
            'country' => 'kz',
            'title' => 'Дом «Сфера»',
            'year' => 'Проект реализован в 2022 году',
            'card_specs' => [
                'Площадь: 190 м²',
                'Этажность: 2 этажа',
                'Коллекция: RE KROVLI XD',
                'Размер: 530x100x40',
                'Цвет: осенний лес',
            ],
            'hero_image' => 'storage/img/sphere.png',
            'hero_alt' => 'Дом Сфера',
            'description' => [],
            'brick_caption' => '',
            'brick_text' => '',
            'characteristics' => [],
            'gallery' => [],
        ],
        [
            'slug' => 'villa-aura',
            'country' => 'ru',
            'title' => 'Вилла «Аура»',
            'year' => 'Проект реализован в 2021 году',
            'card_specs' => [
                'Площадь: 420 м²',
                'Этажность: 2 этажа',
                'Коллекция: RE KRA pod illum 490',
                'Размер: 530x100x40',
                'Цвет: тёмный беж',
            ],
            'hero_image' => 'storage/img/aura.png',
            'hero_alt' => 'Вилла Аура',
            'description' => [],
            'brick_caption' => '',
            'brick_text' => '',
            'characteristics' => [],
            'gallery' => [],
        ],
        [
            'slug' => 'loft-zenit',
            'country' => 'by',
            'title' => 'Лофт «Зенит»',
            'year' => 'Проект реализован в 2020 году',
            'card_specs' => [
                'Площадь: 210 м²',
                'Этажность: 1 этаж',
                'Коллекция: RE KROVLI loft',
                'Размер: 530x100x40',
                'Цвет: коричневый',
            ],
            'hero_image' => 'storage/img/zenit.png',
            'hero_alt' => 'Лофт Зенит',
            'description' => [],
            'brick_caption' => '',
            'brick_text' => '',
            'characteristics' => [],
            'gallery' => [],
        ],
    ],
];
